<?php

namespace CodersLabBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneboookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneboookRepository extends EntityRepository
{
}
